# Dependencies
markdown: redcarpet
plugins: [jekyll-paginate]

# Permalinks
permalink: none

# Setup
title: Codedna.me
description: It is God’s privilege to conceal things and [our] privilege to discover them. -Proverbs 25:2
url: https://dettweilerjs.github.io
baseurl: /

#author:
#  name: 'Joel Dettweiler'
#  url: 

paginate: 5
